--- 
redirects: 
  advanced/automated: ./library/advanced/environment-variables.md
  advanced/grouping: ./library/advanced/grouping.md
  advanced/limits: ./library/advanced/limits.md
  advanced/resuming: ./library/advanced/resuming.md
  advanced/security: ./library/advanced/security.md
  alerts/slack: ./app/features/alerts.md
  api: ./library/api/README.md
  api/overview: ./library/api/README.md
  api/project: ./library/api/README.md
  api/run: ./library/api/README.md
  cli/overview: ./library/cli.md
  cli/restoring: ./library/cli.md
  docs/: ./README.md
  docs/automated: ./advanced/environment-variables.md
  docs/advanced/automated: ./library/advanced/environment-variables.md
  docs/advanced/grouping: ./library/advanced/grouping.md
  docs/advanced/limits: ./library/advanced/limits.md
  docs/advanced/resuming: ./library/advanced/resuming.md
  docs/advanced/security: ./library/advanced/security.md
  docs/alerts/slack: ./app/features/alerts.md
  docs/api: ./library/api/README.md
  docs/api/overview: ./library/api/README.md
  docs/api/project: ./library/api/README.md
  docs/api/run: ./library/api/README.md
  docs/artifacts: ./library/python/init.md
  docs/examples: ./library/example-projects/README.md
  docs/cli/overview: ./library/cli.md
  docs/cli/restoring: ./library/cli.md
  docs/config: ./library/python/config.md
  docs/enterprise/about: ./enterprise/overview.md
  docs/enterprise/cloud/about: ./enterprise/cloud.md
  docs/enterprise/server/about: ./enterprise/overview.md
  docs/enterprise/server/config: ./enterprise/server/configuration.md
  docs/enterprise/server/setup: ./enterprise/overview.md
  docs/enterprise/server/upgrades: ./enterprise/server/upgrades.md
  docs/enterprise/usage/sending-data: ./enterprise/sending-data.md
  docs/faq: ./overview/company-faq.md
  docs/frameworks/catalyst: ./library/integrations/catalyst.md
  docs/frameworks/examples: ./library/example-projects.md
  docs/frameworks/fastai: ./library/frameworks/fastai.md
  docs/frameworks/fastai-example: ./library/example-projects/fastai.md
  docs/frameworks/jax-example: ./library/example-projects/jax.md
  docs/frameworks/keras: ./library/frameworks/keras.md
  docs/frameworks/keras-example: ./library/example-projects/keras.md
  docs/frameworks/numpy-example: ./library/example-projects/numpy.md
  docs/frameworks/pytorch: ./library/frameworks/pytorch.md
  docs/frameworks/pytorch-example: ./library/example-projects/pytorch.md
  docs/frameworks/scikit: ./library/frameworks/scikit.md
  docs/frameworks/scikit-example: ./library/example-projects/scikit.md
  docs/frameworks/tensorflow: ./library/frameworks/tensorflow.md
  docs/frameworks/tensorflow-example: ./library/example-projects/tensorflow.md
  docs/frameworks/xgboost: ./library/frameworks/xgboost.md
  docs/frameworks/xgboost-example: ./library/example-projects/xgboost.md
  docs/getting-started: ./quickstart.md
  docs/init: ./library/python/init.md
  docs/integrations/api: ./library/api/README.md
  ? "docs/integrations/api#special-methods"
  : ./library/api/README.md
  docs/integrations/databricks: ./library/integrations/databricks.md
  docs/integrations/docker: ./library/integrations/docker.md
  docs/integrations/jupyter: ./library/integrations/jupyter.md
  docs/integrations/kubeflow: ./library/integrations/kubeflow.md
  docs/integrations/ray: ./library/integrations/ray.md
  docs/integrations/sagemaker: ./library/integrations/sagemaker.md
  docs/integrations/tensorboard: ./library/integrations/tensorboard.md
  docs/log: ./library/python/log.md
  docs/logs: ./library/python/log.md
  ? "docs/log#summary-metrics"
  : "./library/python/log#summary-metrics.md"
  docs/overview/company-faq: ./overview/company-faq.md
  docs/overview/getting-help: ./overview/getting-help.md
  docs/overview/overview: ./overview.md
  docs/overview/technical-faq: ./overview/technical-faq.md
  docs/restore: ./library/python/restore.md
  docs/save: ./library/python/save.md
  docs/started: ./quickstart.md
  docs/sweeps/configuration: ./library/sweeps/configuration.md
  docs/sweeps/local: ./library/sweeps/local-controller.md
  docs/sweeps/overview: ./library/sweeps.md
  docs/sweeps/python: ./library/sweeps/python-api.md
  docs/wandb/config: ./library/python/config.md
  docs/wandb/init: ./library/python/init.md
  docs/wandb/log: ./library/python/log.md
  docs/wandb/restore: ./library/python/restore.md
  docs/wandb/save: ./library/python/save.md
  en/help: ./README.md
  enterprise/about: ./enterprise/overview.md
  enterprise/cloud/about: ./enterprise/cloud.md
  enterprise/server/about: ./enterprise/overview.md
  enterprise/server/config: ./enterprise/server/configuration.md
  enterprise/server/setup: ./enterprise/overview.md
  enterprise/server/upgrades: ./enterprise/server/upgrades.md
  enterprise/usage/sending-data: ./enterprise/sending-data.md
  frameworks/catalyst: ./library/integrations/catalyst.md
  frameworks/examples: ./library/example-projects.md
  frameworks/fastai: ./library/frameworks/fastai.md
  frameworks/fastai-example: ./library/example-projects/fastai.md
  frameworks/jax-example: ./library/example-projects/jax.md
  frameworks/keras: ./library/frameworks/keras.md
  frameworks/keras-example: ./library/example-projects/keras.md
  frameworks/numpy-example: ./library/example-projects/numpy.md
  frameworks/pytorch: ./library/frameworks/pytorch.md
  frameworks/pytorch-example: ./library/example-projects/pytorch.md
  frameworks/scikit: ./library/frameworks/scikit.md
  frameworks/scikit-example: ./library/example-projects/scikit.md
  frameworks/tensorflow: ./library/frameworks/tensorflow.md
  frameworks/tensorflow-example: ./library/example-projects/tensorflow.md
  frameworks/xgboost: ./library/frameworks/xgboost.md
  frameworks/xgboost-example: ./library/example-projects/xgboost.md
  getting-started: ./quickstart.md
  integrations/api: ./library/api/README.md
  ? "integrations/api#special-methods"
  : ./library/api/README.md
  integrations/databricks: ./library/integrations/databricks.md
  integrations/docker: ./library/integrations/docker.md
  integrations/jupyter: ./library/integrations/jupyter.md
  integrations/kubeflow: ./library/integrations/kubeflow.md
  integrations/ray: ./library/integrations/ray.md
  integrations/sagemaker: ./library/integrations/sagemaker.md
  integrations/tensorboard: ./library/integrations/tensorboard.md
  overview/company-faq: ./overview/company-faq.md
  overview/getting-help: ./overview/getting-help.md
  overview/overview: ./overview.md
  overview/technical-faq: ./overview/technical-faq.md
  sweeps/configuration: ./library/sweeps/configuration.md
  sweeps/local: ./library/sweeps/local-controller.md
  sweeps/overview: ./library/sweeps.md
  sweeps/python: ./library/sweeps/python-api.md
  wandb/config: ./library/python/config.md
  wandb/init: ./library/python/init.md
  wandb/log: ./library/python/log.md
  wandb/restore: ./library/python/restore.md
  wandb/save: ./library/python/save.md
